### ISSUE TITLE
openeo api version hardcoded to 1.0.0

### ISSUE THREAD

**Issue by guss84** [Open-EO/openeo-sentinelhub-python-driver#56]
We are currently stating that we are using openeo version 1.0.0 at https://openeo.sentinel-hub.com/production/ and https://openeo.sentinel-hub.com/production/.well-known/openeo. Ideally we should be using 1.2.0 or 1.1.0.

- Check the documentation and identify we are 1.2.0 compliant
- Change the hardcode version to the correct version

**Comment by zcernigoj** [comment]
# [1.0.1 - 2020-12-07](https://github.com/Open-EO/openeo-api/releases/tag/1.0.1)
## Changed
- [ ] GET /collections and GET /collections/{collection_id}: Units for STAC dimensions in cube:dimensions should be compliant to UDUNITS-2 units (singular) whenever available.
  - **NOTE:** `m` (`symbol` from [UDUNITS-2](https://docs.unidata.ucar.edu/udunits/current/udunits2-base.xml)) is used; `singular` in [UDUNITS-2](https://docs.unidata.ucar.edu/udunits/current/udunits2-base.xml) is `meter`
  - **NOTE:** `degree` is ok per [UDUNITS-2 accepted units](https://docs.unidata.ucar.edu/udunits/current/udunits2-accepted.xml)
- [x] GET /file_formats: It is recommended to at least specify one of the data types in gis_data_types. [#325](https://github.com/Open-EO/openeo-api/issues/325)

## Fixed
- [ ] Cross-Origin Resource Sharing (CORS):
  - [ ] SECURITY: It is recommended to set `Access-Control-Allow-Origin` to `*` instead of reflecting the origin. [#41](https://github.com/Open-EO/openeo-api/issues/41)
    - **NOTE:** `Access-Control-Allow-Origin` is still set to refrect the origin
  - [ ] SECURITY: It is recommended to NOT send the Access-Control-Allow-Credentials header any more. [#41](https://github.com/Open-EO/openeo-api/issues/41)
    - **NOTE:** `Access-Control-Allow-Credentials` header is still sent
  - [ ] Added missing Link header to Access-Control-Expose-Headers. [#331](https://github.com/Open-EO/openeo-api/issues/331)
    - **NOTE:** not added
- [ ] `GET /`: Missing option `OPTIONS` added to allowed `methods` for the `endpoints`. [#324](https://github.com/Open-EO/openeo-api/issues/324)
  - **NOTE:** not added
- [x] For `PATCH` requests: Clarified that no default values apply (for `budget`, `enabled` and `plan`). Data is only changed on the back-end if new data is explicitly specified by the client.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] For `POST` requests with a `plan` property: Clarify that the default value is `null`.
  - **NOTE:** `trial` is used as default in SH openEO backend
- [x] `GET /jobs/{job_id}/results`: Clarified the use of the `type` `Feature` in the GeoJSON result response. [#327](https://github.com/Open-EO/openeo-api/issues/327)
  - **NOTE:** SH openEO backend doesn't support results in GeoJSON format
- [x] Add missing `{namespace}` placeholder to `ProcessUnsupported` error message. [#328](https://github.com/Open-EO/openeo-api/issues/328)
  - **NOTE:** `namespace` hardcoded to `Sentinel Hub`; comment in the code: `Not sure what the namespace is supposed to be`
- [x] Fixed JSON Schema links to point to draft-07 instead of draft/2019-09.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] GET /jobs/{job_id}/estimate: Enforce in the response schema that "at least one of costs, duration or size MUST be provided."
  - **NOTE:** response always contains params `costs`, `size`

---

Note: [VITO's backend](https://openeo.vito.be/openeo/) doesn't comply with all those, but the version reported there is `1.2.0`

**Comment by zcernigoj** [comment]
# [[1.1.0] - 2021-05-17](https://github.com/Open-EO/openeo-api/releases/tag/1.1.0)
## Added

- [ ] GET /processes and GET / PUT for /process_graphs/{process_graph_id}: Allow specifying the return values processes receive from child processes. [#350](https://github.com/Open-EO/openeo-api/issues/350)
  - **NOTE:** `processes` are anyway cloned from https://github.com/Open-EO/openeo-processes.git
  - **NOTE:** don't know how to create a new pg in editor to test `/process_graphs/{process_graph_id}` 
- [x] Recommendation that POST /result returns a tar file if the result consists of multiple files. [#349](https://github.com/Open-EO/openeo-api/issues/349)
  - **NOTE:** SH openEO backend uses SH Process API in a way there is **always 1 file returned** (temporal dimension as `bands`). Might change if post-processing is enabled also for sync requests.
- [x] GET /credentials/oidc can provide a set of default client ids for OpenID Connect. [#366](https://github.com/Open-EO/openeo-api/issues/366)
- [x] experimental and deprecated flags added for file formats, service types, udf runtimes, udf runtime versions, udf runtime libraries and all related parameters and schemas. [#354](https://github.com/Open-EO/openeo-api/issues/354)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] GET /jobs/{job_id} and GET /services/{service_id}: usage property added for usage metrics. [#370](https://github.com/Open-EO/openeo-api/issues/370)
  - **NOTE:** `GET /jobs/{job_id}` YES, `GET /services/{service_id` NO
- [ ] GET /jobs/{job_id}/logs and GET /services/{service_id}/logs:
  - [ ] time property added. [#330](https://github.com/Open-EO/openeo-api/issues/330)
    - **NOTE:** no for either
  - [ ] usage property added to log entries. [#370](https://github.com/Open-EO/openeo-api/issues/370)
    - **NOTE:** no for either
- [ ] Added error ResultLinkExpired. [#379](https://github.com/Open-EO/openeo-api/issues/379)
  - **NOTE:** Not added; not sure how to add it since it's AWS S3 link and AWS handles the expired links errors
- [x] GET /me: A default plan per user can be specified. [#375](https://github.com/Open-EO/openeo-api/issues/375)

## Changed

- [x] API doesn't discourage usage of multipleOf in JSON Schemas any longer.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] GET /jobs/{job_id}/results supports to return a STAC Collection. [#343](https://github.com/Open-EO/openeo-api/issues/343)
  - **NOTE:** SH openEO backend returns `"type": "Feature"`
- [x] Updated STAC schemas to better support versions 1.x.x.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] The first extent in a Collection is always the overall extent, followed by more specific extents. [#369](https://github.com/Open-EO/openeo-api/issues/369)
  - **NOTE:** SH openEO collections always have only 1 extent

## Fixed

- [x] Clarified how process exceptions should be used. [#352](https://github.com/Open-EO/openeo-api/issues/352)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified that job results schould be stored as valid STAC catalogs. [#363](https://github.com/Open-EO/openeo-api/issues/363)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified that job results require the property datetime and allow for additional properties. [#362](https://github.com/Open-EO/openeo-api/issues/362)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified that billing plans, service names and file formats must be accepted case-insensitive. [#371](https://github.com/Open-EO/openeo-api/issues/371)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified that the first provider listed at GET /credentials/oidc is the default provider for OpenID Connect.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified that GET /jobs/{job_id}/results should always return valid signed URLs and the endpoint can be used to renew the signed URLs. [#379](https://github.com/Open-EO/openeo-api/issues/379)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Fixed casing of potential endpoints GET /collections/{collection_id}/items and GET /collections/{collection_id}/items/{feature_id}.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend. Also, SH openEO backend does not support those endpoints (yet).
- [x] Clarified allowed characters in the path for uploaded user files.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend

**Comment by zcernigoj** [comment]
# [[1.2.0] - 2021-05-25](https://github.com/Open-EO/openeo-api/releases/tag/1.2.0)
## Added

- [ ] New extensions:
  - [x] Commercial Data Extension
    - **NOTE:** I guess SH openEO backend uses it for commercial data
  - [ ] Federation Extension
    - **NOTE:** Not used in SH openEO backend. Not sure if it should be.
- [ ] GET /: New Relation types: [#404](https://github.com/Open-EO/openeo-api/issues/4)
  - [ ] create-form to link to the registration page
    - **NOTE:** I have no idea what that should look like. Vito doesn't have it (?).
  - [ ] recovery-form to link to the credentials recovery page.
    - **NOTE:** I have no idea what that should look like. Vito doesn't have it (?).
- [ ] GET /file_formats: Add pointcloud to the gis_data_types. [#475](https://github.com/Open-EO/openeo-api/issues/47)
  - **NOTE:** SH openEO backend doesn't support pointcloud
- [ ] GET /me: New Relation types alternate and related for user-specific external pages. [#404](https://github.com/Open-EO/openeo-api/issues/4)
  - **NOTE:** ?
- [ ] GET /credentials/oidc: Allow authorization_code and urn:ietf:params:oauth:grant-type:device_code (both without PKCE) as grants for default_clients. [#410](https://github.com/Open-EO/openeo-api/issues/410)
  - **NOTE:** not supported
- [ ] GET /jobs and GET /jobs/{job_id}: Added a links property that can for example link to results and logs. [#453](https://github.com/Open-EO/openeo-api/issues/453)
  - **NOTE:** `GET /jobs` has `link`, `GET /jobs/{job_id}` doesn't
- [ ] GET /jobs/{job_id}/results:
  - [x] Recommendation to add a link with relation type canonical which points to a signed URL with the same content as the response. [#397](https://github.com/Open-EO/openeo-api/issues/397)
  - [ ] Added metadata field openeo:status to indicate the job status (and whether the result is complete or not).
    - **NOTE:** not added
  - [ ] Added parameter partial to allow retrieving incomplete results, which must also add the new property openeo:status to the metadata. [#430](https://github.com/Open-EO/openeo-api/issues/430)
    - **NOTE:** not supported
- [ ] GET /jobs/{job_id}/logs, GET /services/{service_id}/logs: Added level parameter to requests to set the minimum log level returned by the response. [#485](https://github.com/Open-EO/openeo-api/issues/485)
  - **NOTE:** `logs` not supported
- [ ] Added property log_level to secondary web service, batch job and synchronous processing endpoints to indicate the minimum severity level that should be stored for logs. [#329](https://github.com/Open-EO/openeo-api/issues/329)
  - **NOTE:** not supported
- [ ] GET /jobs/{job_id}/logs, GET /services/{service_id}/logs and POST /result: Added level property in responses to reflect the minimum log level that may appear in the response. [#329](https://github.com/Open-EO/openeo-api/issues/329)
  - **NOTE:** `logs` not supported
- [ ] Recommendation to add media types and titles to links for a better user experience.
  - **NOTE:** not everywhere
- [ ] Allow the relation type canonical to be used generally for (shared) resources (e.g. UDPs or batch jobs) without requiring Bearer authentication. [#405](https://github.com/Open-EO/openeo-api/issues/405)
  - **NOTE:** not sure how to create user defined pg
- [ ] Recommendation for UDF runtime names. [#409](https://github.com/Open-EO/openeo-api/issues/409)
  - **NOTE:** not sure how to create user defined pg
- [ ] Processes: Added dimensions schema for subtype datacube
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Collections: Added geometry dimension type to cube:dimensions
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] New endpoint for metadata filters (queryables): /collections/{collection_id}/queryables. Also adds a new rel type to the collection links. [#396](https://github.com/Open-EO/openeo-api/issues/396)
  - **NOTE:** Not supported

## Changed

- [ ] Updated STAC specification examples and references to v1.0.0, please see the STAC changelog for all changes between 0.9 and 1.0.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] cube:dimensions: reference_system is allowed to be PROJJSON, too.
  - **NOTE:** PROJJSON not supported
- [x] Relaxed requirement that unsupported endpoints must return HTTP status code 501. Instead also HTTP status code 404 can be used (and is regularly used in practice). [#415](https://github.com/Open-EO/openeo-api/issues/415)
  - **NOTE:** 404 is returned for any endpoint that is not set in `app.py`
- [ ] Minimum value for costs and budget is 0.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] GET /jobs/{job_id}/estimate: If a batch job can't be estimated reliably, a EstimateComplexity error should be returned. #443
  - **NOTE:** Currently not implemented yet, but could be used when estimation would take too much time.
- [ ] The /conformance endpoint is now generally used for OGC APIs, STAC API and openEO. conformsTo is also exposed in GET / for STAC APIs. The openEO API and all extensions got individual conformance classes. [#186](https://github.com/Open-EO/openeo-api/issues/186)
  - **NOTE:** `/conformance` endpoint not implemented

## Fixed

- [ ] Explicitly mention the use of HTTP content negotiation
  - **NOTE:** Not sure if anything is needed in the SH openEO backend. 
- [ ] Clarify that the default charset is UTF-8 [#462](https://github.com/Open-EO/openeo-api/issues/462)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Fixed inconsistencies in errors.json: removed ProcessGraphIdDoesntMatch, clarified ProcessGraphMissing, added ProcessInvalid and ProcessGraphInvalid. [#394](https://github.com/Open-EO/openeo-api/issues/394), [#395](https://github.com/Open-EO/openeo-api/issues/395), [#401](https://github.com/Open-EO/openeo-api/issues/401)
  - **NOTE:** Not updated yet
- [ ] Fixed the default value for the version number in the API url (v1.0 -> v1) and improved the description for API versioning. [#393](https://github.com/Open-EO/openeo-api/issues/393)
  - **NOTE:** SH openEO backend does not use version in URL
- [x] Fixed the Collection example to use gsd instead of eo:gsd. [#399](https://github.com/Open-EO/openeo-api/issues/399)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarify use of user_id. [#404](https://github.com/Open-EO/openeo-api/issues/404)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Clarify that the relation type version-history should include /.well-known/openeo in the URL.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Clarify that clients should (re-)request capabilities and discovery endpoints with token if available and supported. [#416](https://github.com/Open-EO/openeo-api/issues/416)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Clarify the fields plan (for processing requests) and billing_plan (in GET / and GET /me). [#425](https://github.com/Open-EO/openeo-api/issues/425) [#426](https://github.com/Open-EO/openeo-api/issues/426)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified ambiguous batch job status changes.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Reflect that the debug process has been renamed to inspect.
  - **NOTE:** Not changed yet
- [x] Clarified uniqueness constraints for identifiers. [#449](https://github.com/Open-EO/openeo-api/issues/449) [#454](https://github.com/Open-EO/openeo-api/issues/454)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] Clarified schematically the applicability of JSON Schema extensions (parameters, returns, dimensions) and their relation to the subtypes
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [x] GET /: Removed the superfluous default value for currency. [#423](https://github.com/Open-EO/openeo-api/issues/423)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend (no currency default value on that endpoint)
- [ ] GET /credentials/oidc: Clarify that clients may add additional scopes
  - **NOTE:** Not sure if anything is needed in the SH openEO backend - something to support?
- [x] GET /me: Clarify the behavior of the field budget.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] GET /jobs/{job_id}/logs, GET /services/{service_id}/logs and POST /result: Clarified the formatting of the message property. [#455](https://github.com/Open-EO/openeo-api/issues/455)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend. `logs` not implemented
- [x] GET /jobs/{job_id}/estimate: Don't require that the costs are the upper limit. Services may specify the costs more freely depending on their terms of service.
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] GET /services and GET /services/{service_id}: Clarify that enabled is required by removing the default value. [#473](https://github.com/Open-EO/openeo-api/issues/473)
  - **NOTE:** default value (which is `True` in SH openEO backend) should be removed
- [ ] Several appearances of nullable were clarified according to the lint report by Spectral
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Clarify how the well-known document works [#460](https://github.com/Open-EO/openeo-api/issues/460)
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
- [ ] Clarify handling of JSON Schema versions
  - **NOTE:** Not sure if anything is needed in the SH openEO backend
